// <auto-generated />
using Artisanaux.Services.ProductAPI.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Artisanaux.Services.ProductAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Artisanaux.Services.ProductAPI.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"), 1L, 1);

                    b.Property<string>("CategoryName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            CategoryName = "Rongement",
                            ImageURL = "https://artisanamf.blob.core.windows.net/artisana/1.jpeg",
                            Price = 1500.0,
                            ProductName = "Espace de Rongement"
                        },
                        new
                        {
                            ProductId = 2,
                            CategoryName = "Rongement",
                            ImageURL = "https://artisanamf.blob.core.windows.net/artisana/2.jpg",
                            Price = 1600.0,
                            ProductName = " Rongement"
                        },
                        new
                        {
                            ProductId = 3,
                            CategoryName = "Rongement",
                            ImageURL = "https://artisanamf.blob.core.windows.net/artisana/3.jpeg",
                            Price = 2600.0,
                            ProductName = " Rongement simple"
                        },
                        new
                        {
                            ProductId = 4,
                            CategoryName = "Rongement",
                            ImageURL = "https://artisanamf.blob.core.windows.net/artisana/4.jpeg",
                            Price = 600.0,
                            ProductName = " Rongement complex"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
